// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         version: "R4",
 *         resource: "auto",
 *         text: "Patient has severe asthma with acute exacerbation"
 *     }
 */
export interface CreateRequest {
    /** FHIR version to use */
    version: string;
    /** Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile. Recommended to use the supported US Core Profiles for validated results but you can also use any custom profile you've uploaded (if you're a develop or launch customer) */
    resource: CreateRequest.Resource;
    /** Natural language text to convert */
    text: string;
}

export namespace CreateRequest {
    /** Type of FHIR resource to create. Use 'auto' for automatic resource type detection, or specify a supported US Core profile. Recommended to use the supported US Core Profiles for validated results but you can also use any custom profile you've uploaded (if you're a develop or launch customer) */
    export const Resource = {
        Auto: "auto",
        Appointment: "appointment",
        ConditionEncounterDiagnosis: "condition-encounter-diagnosis",
        Medicationrequest: "medicationrequest",
        Careplan: "careplan",
        ConditionProblemsHealthConcerns: "condition-problems-health-concerns",
        Coverage: "coverage",
        Encounter: "encounter",
        ObservationClinicalResult: "observation-clinical-result",
        ObservationLab: "observation-lab",
        Patient: "patient",
        Procedure: "procedure",
        Questionnaire: "questionnaire",
        Questionnaireresponse: "questionnaireresponse",
        SimpleObservation: "simple-observation",
        VitalSigns: "vital-signs",
    } as const;
    export type Resource = (typeof Resource)[keyof typeof Resource];
}
