// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../../index.js";

/**
 * @example
 *     {
 *         version: "R4",
 *         resource: "questionnaire",
 *         content: "JVBERi0xLjQKJeLjz9MK...(base64-encoded document bytes)"
 *     }
 */
export interface DocumentRequest {
    /** FHIR version to use */
    version: string;
    /** Type of FHIR resource to create. Accepts any FHIR resource type or US Core profile name. */
    resource: string;
    /**
     * Base64 encoded file content.
     * Supported file types: PDF (application/pdf), PNG (image/png), JPEG (image/jpeg), TIFF (image/tiff), RTF (application/rtf), XML/C-CDA (text/xml).
     * RTF and XML/C-CDA uploads are available on dedicated instances only.
     * File type is auto-detected from content magic bytes.
     * The decoded file must not exceed 20 MiB. RTF and XML/C-CDA documents whose extracted text exceeds 1 MiB are rejected.
     * Generic XML must include an XML declaration; C-CDA documents rooted at `ClinicalDocument` may omit it.
     */
    content: string;
    config?: phenoml.lang2Fhir.DocumentConfig;
}
