// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         version: "R4",
 *         content: "content"
 *     }
 */
export interface DocumentMultiRequest {
    /** FHIR version to use */
    version: string;
    /**
     * Base64 encoded file content.
     * Supported file types: PDF (application/pdf), PNG (image/png), JPEG (image/jpeg).
     * File type is auto-detected from content magic bytes.
     */
    content: string;
    /** Optional FHIR provider name for provider-specific profiles */
    provider?: string;
}
