// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         version: "R4",
 *         resource: "condition-encounter-diagnosis",
 *         profile: "(base64 encoded JSON string of the FHIR profile)"
 *     }
 */
export interface ProfileUploadRequest {
    /** FHIR version that this profile implements */
    version: string;
    /** Name for the custom resource profile (will be converted to lowercase) */
    resource: string;
    /** Base64 encoded JSON string of the FHIR StructureDefinition profile */
    profile: string;
}
