// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../index.js";

export type FhirSearchResponse = PhenoML.fhir.FhirBundle | PhenoML.fhir.FhirResource;
