// This file was auto-generated by Fern from our API Definition.

/**
 * A generic FHIR resource. All FHIR resources share common elements like resourceType and id,
 * but the specific structure depends on the resource type.
 */
export interface FhirResource {
    /** The type of FHIR resource (e.g., Patient, Observation, etc.) */
    resourceType: string;
    /** Logical ID of the resource */
    id?: string | undefined;
    /** Metadata about the resource */
    meta?: FhirResource.Meta | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace FhirResource {
    /**
     * Metadata about the resource
     */
    export interface Meta {
        versionId?: string | undefined;
        lastUpdated?: string | undefined;
        profile?: string[] | undefined;
    }
}
