// This file was auto-generated by Fern from our API Definition.

import { phenomlClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockPhenoMloAuth } from "../mockAuth";

describe("FhirClient", () => {
    test("search (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            resourceType: "Bundle",
            total: 2,
            entry: [{ resource: { resourceType: "Patient", id: "123", name: [{ family: "Doe", given: ["John"] }] } }],
        };

        server
            .mockEndpoint()
            .get("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.search("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("search (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { resourceType: "Patient", id: "123", name: [{ family: "Doe", given: ["John"] }] };

        server
            .mockEndpoint()
            .get("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.search("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resourceType: "Patient" };
        const rawResponseBody = {
            resourceType: "Patient",
            id: "456",
            meta: { versionId: "1", lastUpdated: "2024-01-15T10:30:00Z" },
        };

        server
            .mockEndpoint()
            .post("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.create("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            body: {
                resourceType: "Patient",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("upsert", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { resourceType: "Patient", id: "123" };
        const rawResponseBody = {
            resourceType: "Patient",
            id: "123",
            meta: { versionId: "2", lastUpdated: "2024-02-20T11:00:00Z" },
        };

        server
            .mockEndpoint()
            .put("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.upsert("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            body: {
                resourceType: "Patient",
                id: "123",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            resourceType: "OperationOutcome",
            issue: [
                { severity: "information", code: "informational", details: { text: "Resource deleted successfully" } },
            ],
        };

        server
            .mockEndpoint()
            .delete("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.delete("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("patch (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [{ op: "replace", path: "/name/0/family", value: "NewFamilyName" }];
        const rawResponseBody = {
            resourceType: "Patient",
            id: "123",
            meta: { versionId: "3", lastUpdated: "2024-02-20T11:30:00Z" },
        };

        server
            .mockEndpoint()
            .patch("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.patch("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            body: [
                {
                    op: "replace",
                    path: "/name/0/family",
                    value: "NewFamilyName",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("patch (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "add", path: "/telecom/-", value: { system: "phone", value: "+1-555-123-4567", use: "home" } },
        ];
        const rawResponseBody = {
            resourceType: "Patient",
            id: "123",
            meta: { versionId: "3", lastUpdated: "2024-02-20T11:30:00Z" },
        };

        server
            .mockEndpoint()
            .patch("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.patch("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            body: [
                {
                    op: "add",
                    path: "/telecom/-",
                    value: {
                        system: "phone",
                        value: "+1-555-123-4567",
                        use: "home",
                    },
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("patch (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "replace", path: "/name/0/family", value: "Smith" },
            { op: "add", path: "/telecom/-", value: { system: "email", value: "john.smith@example.com" } },
            { op: "remove", path: "/address/0" },
        ];
        const rawResponseBody = {
            resourceType: "Patient",
            id: "123",
            meta: { versionId: "3", lastUpdated: "2024-02-20T11:30:00Z" },
        };

        server
            .mockEndpoint()
            .patch("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.patch("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            body: [
                {
                    op: "replace",
                    path: "/name/0/family",
                    value: "Smith",
                },
                {
                    op: "add",
                    path: "/telecom/-",
                    value: {
                        system: "email",
                        value: "john.smith@example.com",
                    },
                },
                {
                    op: "remove",
                    path: "/address/0",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("patch (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "test", path: "/gender", value: "male" },
            { op: "replace", path: "/gender", value: "female" },
        ];
        const rawResponseBody = {
            resourceType: "Patient",
            id: "123",
            meta: { versionId: "3", lastUpdated: "2024-02-20T11:30:00Z" },
        };

        server
            .mockEndpoint()
            .patch("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir/Patient")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.patch("550e8400-e29b-41d4-a716-446655440000", "Patient", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            body: [
                {
                    op: "test",
                    path: "/gender",
                    value: "male",
                },
                {
                    op: "replace",
                    path: "/gender",
                    value: "female",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("executeBundle", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            resourceType: "Bundle",
            type: "transaction",
            entry: [
                {
                    request: { method: "POST", url: "Patient" },
                    resource: { resourceType: "Patient", name: [{ family: "Doe", given: ["John"] }] },
                },
                {
                    request: { method: "POST", url: "Observation" },
                    resource: { resourceType: "Observation", status: "final", subject: { reference: "Patient/123" } },
                },
            ],
        };
        const rawResponseBody = {
            resourceType: "Bundle",
            type: "transaction-response",
            entry: [
                {
                    response: { status: "201 Created", location: "Patient/456" },
                    resource: { resourceType: "Patient", id: "456" },
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/fhir-provider/550e8400-e29b-41d4-a716-446655440000/fhir")
            .header("X-Phenoml-On-Behalf-Of", "Patient/550e8400-e29b-41d4-a716-446655440000")
            .header(
                "X-Phenoml-Fhir-Provider",
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.fhir.executeBundle("550e8400-e29b-41d4-a716-446655440000", {
            "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
            "X-Phenoml-Fhir-Provider":
                "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
            body: {
                resourceType: "Bundle",
                type: "transaction",
                entry: [
                    {
                        request: {
                            method: "POST",
                            url: "Patient",
                        },
                        resource: {
                            resourceType: "Patient",
                            name: [
                                {
                                    family: "Doe",
                                    given: ["John"],
                                },
                            ],
                        },
                    },
                    {
                        request: {
                            method: "POST",
                            url: "Observation",
                        },
                        resource: {
                            resourceType: "Observation",
                            status: "final",
                            subject: {
                                reference: "Patient/123",
                            },
                        },
                    },
                ],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });
});
