// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../../index.js";

/**
 * @example
 *     {
 *         "X-Phenoml-On-Behalf-Of": "user@example.com",
 *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
 *         fhir_path: "Patient",
 *         body: {
 *             resourceType: "Patient",
 *             name: [
 *                 {
 *                     "family": "Doe",
 *                     "given": [
 *                         "Jane"
 *                     ]
 *                 }
 *             ],
 *             gender: "female",
 *             birthDate: "1990-01-01"
 *         }
 *     }
 */
export interface CreateFhirRequest {
    /**
     * The ID of the FHIR provider to use. Can be either:
     * - A UUID representing the provider ID
     * - A provider name (legacy support - will just use the most recently updated provider with this name)
     */
    fhir_provider_id: string;
    /**
     * The FHIR resource path to operate on. This follows FHIR RESTful API conventions.
     * Examples:
     * - "Patient" (for resource type operations)
     * - "Patient/123" (for specific resource operations)
     * - "Patient/123/_history" (for history operations)
     */
    fhir_path: string;
    /** Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity. */
    "X-Phenoml-On-Behalf-Of"?: string;
    body: phenoml.fhir.FhirResource;
}
