// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../../index.js";

/**
 * @example
 *     {
 *         "X-Phenoml-On-Behalf-Of": "user@example.com",
 *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
 *         body: {
 *             resourceType: "Bundle",
 *             entry: [{
 *                     resource: {
 *                         "resourceType": "Patient",
 *                         "name": [
 *                             {
 *                                 "family": "Doe",
 *                                 "given": [
 *                                     "John"
 *                                 ]
 *                             }
 *                         ]
 *                     },
 *                     request: {
 *                         method: "POST",
 *                         url: "Patient"
 *                     }
 *                 }, {
 *                     resource: {
 *                         "resourceType": "Observation",
 *                         "status": "final",
 *                         "subject": {
 *                             "reference": "Patient/123"
 *                         }
 *                     },
 *                     request: {
 *                         method: "POST",
 *                         url: "Observation"
 *                     }
 *                 }]
 *         }
 *     }
 */
export interface ExecuteBundleFhirRequest {
    /**
     * The ID of the FHIR provider to use. Can be either:
     * - A UUID representing the provider ID
     * - A provider name (legacy support - will just use the most recently updated provider with this name)
     */
    fhir_provider_id: string;
    /** Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity. */
    "X-Phenoml-On-Behalf-Of"?: string;
    body: phenoml.fhir.FhirBundle;
}
