// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../../index.js";

/**
 * @example
 *     {
 *         "X-Phenoml-On-Behalf-Of": "Patient/550e8400-e29b-41d4-a716-446655440000",
 *         "X-Phenoml-Fhir-Provider": "550e8400-e29b-41d4-a716-446655440000:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c...",
 *         body: {
 *             resourceType: "Bundle",
 *             entry: [{
 *                     resource: {
 *                         "resourceType": "Patient",
 *                         "name": [
 *                             {
 *                                 "family": "Doe",
 *                                 "given": [
 *                                     "John"
 *                                 ]
 *                             }
 *                         ]
 *                     },
 *                     request: {
 *                         method: "POST",
 *                         url: "Patient"
 *                     }
 *                 }, {
 *                     resource: {
 *                         "resourceType": "Observation",
 *                         "status": "final",
 *                         "subject": {
 *                             "reference": "Patient/123"
 *                         }
 *                     },
 *                     request: {
 *                         method: "POST",
 *                         url: "Observation"
 *                     }
 *                 }]
 *         }
 *     }
 */
export interface FhirExecuteBundleRequest {
    /**
     * Optional header for on-behalf-of authentication. Used when making requests on behalf of another user or entity.
     * Must be in the format: Patient/{uuid} or Practitioner/{uuid}
     */
    "X-Phenoml-On-Behalf-Of"?: string;
    /**
     * Optional header for FHIR provider authentication. Contains credentials in the format {fhir_provider_id}:{oauth2_token}.
     * Multiple FHIR provider integrations can be provided as comma-separated values.
     */
    "X-Phenoml-Fhir-Provider"?: string;
    body: phenoml.fhir.FhirBundle;
}
