// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

/**
 * A FHIR StructureDefinition as a JSON object. Must include resourceType: StructureDefinition, url, type, version, and a snapshot with elements. The canonical URL and resource type must match the profile when one already exists. If id is present, its lowercased value must match the path id; if omitted, the path id is used. The version may contain letters, numbers, and the punctuation characters `.`, `_`, `~`, `+`, and `-`; it cannot be exactly `.` or `..`.
 */
export type ProfileVersionCreateRequest = phenoml.profiles.FhirResource;
