// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         text: "female patients over 20 with diabetes but not hypertension",
 *         provider: "550e8400-e29b-41d4-a716-446655440000"
 *     }
 */
export interface CohortRequest {
    /** Natural language text describing the patient cohort criteria */
    text: string;
    /** FHIR provider ID - must be a valid UUID from existing FHIR providers. also supports provider by name (e.g. medplum) */
    provider: string;
}
