/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as phenoml from "../../../../index.js";

/**
 * @example
 *     {
 *         text: "Find all appointments for patient John Doe next week"
 *     }
 */
export interface Lang2FhirAndSearchRequest {
    /** Natural language text to convert to FHIR search parameters */
    text: string;
    /** Patient ID to filter results */
    patient_id?: string;
    /** Practitioner ID to filter results */
    practitioner_id?: string;
    /** Maximum number of results to return */
    count?: number;
    /** FHIR provider to use for searching */
    provider?: Lang2FhirAndSearchRequest.Provider;
    meta?: phenoml.tools.FhirClientConfig;
}

export namespace Lang2FhirAndSearchRequest {
    /**
     * FHIR provider to use for searching
     */
    export type Provider = "medplum" | "google_healthcare" | "canvas" | "hapi";
    export const Provider = {
        Medplum: "medplum",
        GoogleHealthcare: "google_healthcare",
        Canvas: "canvas",
        Hapi: "hapi",
    } as const;
}
