// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../../../../index.js";

/**
 * @example
 *     {
 *         implementation_guide: {
 *             resourceType: "ImplementationGuide",
 *             url: "url",
 *             version: "version"
 *         },
 *         profile_refs: ["profile_refs"]
 *     }
 */
export interface CreateCanonicalImplementationGuideRequest {
    implementation_guide: phenoml.implementationGuides.FhirImplementationGuide;
    /** Exact canonical `url|version` references to builtin or custom profiles. A package can contain at most 250 references. */
    profile_refs: string[];
    /** Natural-language profile-selection context for this package. */
    profile_context?: string;
}
