// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../index.js";

export interface AgentGetChatMessagesResponse {
    messages?: PhenoML.agent.ChatMessageTemplate[] | undefined;
    total?: number | undefined;
    session_id?: string | undefined;
}
