// This file was auto-generated by Fern from our API Definition.

export interface AgentChatResponse {
    /** Agent's response */
    response?: string;
    success?: boolean;
    /** Status message */
    message?: string;
    /** Chat session ID */
    session_id?: string;
}
