// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../index.js";

export interface AgentPromptsResponse {
    success?: boolean | undefined;
    message?: string | undefined;
    data?: PhenoML.agent.PromptTemplate | undefined;
}
