// This file was auto-generated by Fern from our API Definition.

export interface AgentChatResponse {
    /** Agent's response */
    response?: string | undefined;
    success?: boolean | undefined;
    /** Status message */
    message?: string | undefined;
    /** Chat session ID */
    session_id?: string | undefined;
}
