// This file was auto-generated by Fern from our API Definition.

export interface ChatSessionTemplate {
    /** Chat session ID */
    id?: string | undefined;
    /** Chat session ID */
    session_id?: string | undefined;
    /** Chat session status */
    status?: string | undefined;
    /** System prompt */
    system_prompt?: string | undefined;
    /** Chat session title */
    title?: string | undefined;
    /** Agent ID */
    agent_id?: string | undefined;
    /** Chat session created time */
    created?: string | undefined;
    /** Chat session last message time */
    last_message_at?: string | undefined;
    /** Chat session updated time */
    updated?: string | undefined;
}
