// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../index.js";

/**
 * RFC 6902 JSON Patch document
 */
export type JsonPatch = PhenoML.agent.JsonPatchOperation[];
