/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PromptTemplate {
    /** Prompt ID */
    id?: string;
    /** Prompt name */
    name?: string;
    /** Prompt description */
    description?: string;
    /** Prompt content */
    content?: string;
    /** Whether this is a default prompt */
    is_default?: boolean;
    /** Whether the prompt is active */
    is_active?: boolean;
    /** Tags for categorizing the prompt */
    tags?: string[];
}
