// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         verbose: true
 *     }
 */
export interface WorkflowsListRequest {
    /** If true, includes full workflow implementation details in workflow_details field */
    verbose?: boolean;
}
