// This file was auto-generated by Fern from our API Definition.

export interface DecisionNodeDefinition {
    /** Simple equality expression for decision logic */
    expression?: string | undefined;
    /** Maps decision outcomes to next step IDs */
    paths?: Record<string, string> | undefined;
    /** Maps placeholder tokens to their input data paths for decision evaluation */
    runtime_placeholders?: Record<string, string> | undefined;
}
