// This file was auto-generated by Fern from our API Definition.

export interface CreateSummaryResponse {
    success?: boolean | undefined;
    message?: string | undefined;
    /** Generated summary text */
    summary?: string | undefined;
    /** Unresolved placeholders or issues (narrative mode only) */
    warnings?: string[] | undefined;
}
