// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

export interface ListTemplatesSummaryResponse {
    success?: boolean;
    templates?: phenoml.summary.SummaryTemplate[];
}
