// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../index.js";

export interface SummaryGetTemplateResponse {
    success?: boolean | undefined;
    template?: PhenoML.summary.SummaryTemplate | undefined;
}
