/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         identity: "identity",
 *         password: "password"
 *     }
 */
export interface AuthGenerateTokenRequest {
    /** The user's username or email */
    identity: string;
    /** The user's password */
    password: string;
}
