// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "username",
 *         password: "password"
 *     }
 */
export interface AuthGenerateTokenRequest {
    /** The API credential client ID */
    username: string;
    /** The API credential client secret */
    password: string;
}
