// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Epic Sandbox",
 *         provider: "athenahealth",
 *         base_url: "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4",
 *         auth: {
 *             auth_method: "jwt",
 *             client_id: "your-client-id"
 *         }
 *     }
 */
export interface FhirProviderCreateRequest {
    /** Display name for the FHIR provider */
    name: string;
    /** Optional description of the FHIR provider */
    description?: string;
    provider: PhenoML.fhirProvider.Provider;
    /** Base URL of the FHIR server */
    base_url: string;
    auth: PhenoML.fhirProvider.FhirProviderCreateRequestAuth;
}
