// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { toJson } from "../../../../core/json.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as phenoml from "../../../index.js";

export declare namespace Fhir {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Fhir {
    protected readonly _options: Fhir.Options;

    constructor(_options: Fhir.Options) {
        this._options = _options;
    }

    /**
     * Retrieves FHIR resources from the specified provider. Supports both individual resource retrieval and search operations based on the FHIR path and query parameters.
     *
     * The request is proxied to the configured FHIR server with appropriate authentication headers.
     *
     * @param {phenoml.fhir.SearchFhirRequest} request
     * @param {Fhir.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.fhir.BadRequestError}
     * @throws {@link phenoml.fhir.UnauthorizedError}
     * @throws {@link phenoml.fhir.NotFoundError}
     * @throws {@link phenoml.fhir.InternalServerError}
     *
     * @example
     *     await client.fhir.search({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient"
     *     })
     */
    public search(
        request: phenoml.fhir.SearchFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): core.HttpResponsePromise<phenoml.fhir.SearchFhirResponse> {
        return core.HttpResponsePromise.fromPromise(this.__search(request, requestOptions));
    }

    private async __search(
        request: phenoml.fhir.SearchFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): Promise<core.WithRawResponse<phenoml.fhir.SearchFhirResponse>> {
        const {
            fhir_provider_id: fhirProviderId,
            fhir_path: fhirPath,
            query_parameters: queryParameters,
            "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (queryParameters != null) {
            _queryParams.query_parameters = toJson(queryParameters);
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf != null ? phenomlOnBehalfOf : undefined,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                `fhir-provider/${core.url.encodePathParam(fhirProviderId)}/fhir/${core.url.encodePathParam(fhirPath)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as phenoml.fhir.SearchFhirResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.fhir.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.fhir.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new phenoml.fhir.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new phenoml.fhir.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.phenomlError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.phenomlTimeoutError(
                    "Timeout exceeded when calling GET /fhir-provider/{fhir_provider_id}/fhir/{fhir_path}.",
                );
            case "unknown":
                throw new errors.phenomlError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates a new FHIR resource on the specified provider. The request body should contain a valid FHIR resource in JSON format.
     *
     * The request is proxied to the configured FHIR server with appropriate authentication headers.
     *
     * @param {phenoml.fhir.CreateFhirRequest} request
     * @param {Fhir.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.fhir.BadRequestError}
     * @throws {@link phenoml.fhir.UnauthorizedError}
     * @throws {@link phenoml.fhir.InternalServerError}
     *
     * @example
     *     await client.fhir.create({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient",
     *         body: {
     *             resourceType: "Patient",
     *             name: [
     *                 {
     *                     "family": "Doe",
     *                     "given": [
     *                         "Jane"
     *                     ]
     *                 }
     *             ],
     *             gender: "female",
     *             birthDate: "1990-01-01"
     *         }
     *     })
     */
    public create(
        request: phenoml.fhir.CreateFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): core.HttpResponsePromise<phenoml.fhir.FhirResource> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: phenoml.fhir.CreateFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): Promise<core.WithRawResponse<phenoml.fhir.FhirResource>> {
        const {
            fhir_provider_id: fhirProviderId,
            fhir_path: fhirPath,
            "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf,
            body: _body,
        } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf != null ? phenomlOnBehalfOf : undefined,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                `fhir-provider/${core.url.encodePathParam(fhirProviderId)}/fhir/${core.url.encodePathParam(fhirPath)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/fhir+json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as phenoml.fhir.FhirResource, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.fhir.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.fhir.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new phenoml.fhir.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.phenomlError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.phenomlTimeoutError(
                    "Timeout exceeded when calling POST /fhir-provider/{fhir_provider_id}/fhir/{fhir_path}.",
                );
            case "unknown":
                throw new errors.phenomlError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates or updates a FHIR resource on the specified provider. If the resource exists, it will be updated; otherwise, it will be created.
     *
     * The request is proxied to the configured FHIR server with appropriate authentication headers.
     *
     * @param {phenoml.fhir.UpsertFhirRequest} request
     * @param {Fhir.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.fhir.BadRequestError}
     * @throws {@link phenoml.fhir.UnauthorizedError}
     * @throws {@link phenoml.fhir.InternalServerError}
     *
     * @example
     *     await client.fhir.upsert({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient",
     *         body: {
     *             resourceType: "Patient",
     *             id: "123",
     *             name: [
     *                 {
     *                     "family": "Doe",
     *                     "given": [
     *                         "John",
     *                         "Updated"
     *                     ]
     *                 }
     *             ],
     *             gender: "male",
     *             birthDate: "1985-05-15"
     *         }
     *     })
     */
    public upsert(
        request: phenoml.fhir.UpsertFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): core.HttpResponsePromise<phenoml.fhir.FhirResource> {
        return core.HttpResponsePromise.fromPromise(this.__upsert(request, requestOptions));
    }

    private async __upsert(
        request: phenoml.fhir.UpsertFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): Promise<core.WithRawResponse<phenoml.fhir.FhirResource>> {
        const {
            fhir_provider_id: fhirProviderId,
            fhir_path: fhirPath,
            "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf,
            body: _body,
        } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf != null ? phenomlOnBehalfOf : undefined,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                `fhir-provider/${core.url.encodePathParam(fhirProviderId)}/fhir/${core.url.encodePathParam(fhirPath)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/fhir+json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as phenoml.fhir.FhirResource, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.fhir.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.fhir.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new phenoml.fhir.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.phenomlError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.phenomlTimeoutError(
                    "Timeout exceeded when calling PUT /fhir-provider/{fhir_provider_id}/fhir/{fhir_path}.",
                );
            case "unknown":
                throw new errors.phenomlError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deletes a FHIR resource from the specified provider.
     *
     * The request is proxied to the configured FHIR server with appropriate authentication headers.
     *
     * @param {phenoml.fhir.DeleteFhirRequest} request
     * @param {Fhir.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.fhir.BadRequestError}
     * @throws {@link phenoml.fhir.UnauthorizedError}
     * @throws {@link phenoml.fhir.NotFoundError}
     * @throws {@link phenoml.fhir.InternalServerError}
     *
     * @example
     *     await client.fhir.delete({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient"
     *     })
     */
    public delete(
        request: phenoml.fhir.DeleteFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: phenoml.fhir.DeleteFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const {
            fhir_provider_id: fhirProviderId,
            fhir_path: fhirPath,
            "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf,
        } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf != null ? phenomlOnBehalfOf : undefined,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                `fhir-provider/${core.url.encodePathParam(fhirProviderId)}/fhir/${core.url.encodePathParam(fhirPath)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.fhir.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.fhir.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new phenoml.fhir.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new phenoml.fhir.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.phenomlError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.phenomlTimeoutError(
                    "Timeout exceeded when calling DELETE /fhir-provider/{fhir_provider_id}/fhir/{fhir_path}.",
                );
            case "unknown":
                throw new errors.phenomlError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Partially updates a FHIR resource on the specified provider using JSON Patch operations as defined in RFC 6902.
     *
     * The request body should contain an array of JSON Patch operations. Each operation specifies:
     * - `op`: The operation type (add, remove, replace, move, copy, test)
     * - `path`: JSON Pointer to the target location in the resource
     * - `value`: The value to use (required for add, replace, and test operations)
     *
     * The request is proxied to the configured FHIR server with appropriate authentication headers.
     *
     * @param {phenoml.fhir.PatchFhirRequest} request
     * @param {Fhir.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.fhir.BadRequestError}
     * @throws {@link phenoml.fhir.UnauthorizedError}
     * @throws {@link phenoml.fhir.NotFoundError}
     * @throws {@link phenoml.fhir.InternalServerError}
     *
     * @example
     *     await client.fhir.patch({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient",
     *         body: [{
     *                 op: "replace",
     *                 path: "/name/0/family",
     *                 value: "NewFamilyName"
     *             }]
     *     })
     *
     * @example
     *     await client.fhir.patch({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient",
     *         body: [{
     *                 op: "add",
     *                 path: "/telecom/-",
     *                 value: {
     *                     "system": "phone",
     *                     "value": "+1-555-123-4567",
     *                     "use": "home"
     *                 }
     *             }]
     *     })
     *
     * @example
     *     await client.fhir.patch({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient",
     *         body: [{
     *                 op: "replace",
     *                 path: "/name/0/family",
     *                 value: "Smith"
     *             }, {
     *                 op: "add",
     *                 path: "/telecom/-",
     *                 value: {
     *                     "system": "email",
     *                     "value": "john.smith@example.com"
     *                 }
     *             }, {
     *                 op: "remove",
     *                 path: "/address/0"
     *             }]
     *     })
     *
     * @example
     *     await client.fhir.patch({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         fhir_path: "Patient",
     *         body: [{
     *                 op: "test",
     *                 path: "/gender",
     *                 value: "male"
     *             }, {
     *                 op: "replace",
     *                 path: "/gender",
     *                 value: "female"
     *             }]
     *     })
     */
    public patch(
        request: phenoml.fhir.PatchFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): core.HttpResponsePromise<phenoml.fhir.FhirResource> {
        return core.HttpResponsePromise.fromPromise(this.__patch(request, requestOptions));
    }

    private async __patch(
        request: phenoml.fhir.PatchFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): Promise<core.WithRawResponse<phenoml.fhir.FhirResource>> {
        const {
            fhir_provider_id: fhirProviderId,
            fhir_path: fhirPath,
            "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf,
            body: _body,
        } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf != null ? phenomlOnBehalfOf : undefined,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                `fhir-provider/${core.url.encodePathParam(fhirProviderId)}/fhir/${core.url.encodePathParam(fhirPath)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json-patch+json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as phenoml.fhir.FhirResource, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.fhir.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.fhir.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new phenoml.fhir.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new phenoml.fhir.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.phenomlError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.phenomlTimeoutError(
                    "Timeout exceeded when calling PATCH /fhir-provider/{fhir_provider_id}/fhir/{fhir_path}.",
                );
            case "unknown":
                throw new errors.phenomlError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Executes a FHIR Bundle transaction or batch operation on the specified provider. This allows multiple FHIR resources to be processed in a single request.
     *
     * The request body should contain a valid FHIR Bundle resource with transaction or batch type.
     *
     * The request is proxied to the configured FHIR server with appropriate authentication headers.
     *
     * @param {phenoml.fhir.ExecuteBundleFhirRequest} request
     * @param {Fhir.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.fhir.BadRequestError}
     * @throws {@link phenoml.fhir.UnauthorizedError}
     * @throws {@link phenoml.fhir.InternalServerError}
     *
     * @example
     *     await client.fhir.executeBundle({
     *         "X-Phenoml-On-Behalf-Of": "user@example.com",
     *         fhir_provider_id: "550e8400-e29b-41d4-a716-446655440000",
     *         body: {
     *             resourceType: "Bundle",
     *             entry: [{
     *                     resource: {
     *                         "resourceType": "Patient",
     *                         "name": [
     *                             {
     *                                 "family": "Doe",
     *                                 "given": [
     *                                     "John"
     *                                 ]
     *                             }
     *                         ]
     *                     },
     *                     request: {
     *                         method: "POST",
     *                         url: "Patient"
     *                     }
     *                 }, {
     *                     resource: {
     *                         "resourceType": "Observation",
     *                         "status": "final",
     *                         "subject": {
     *                             "reference": "Patient/123"
     *                         }
     *                     },
     *                     request: {
     *                         method: "POST",
     *                         url: "Observation"
     *                     }
     *                 }]
     *         }
     *     })
     */
    public executeBundle(
        request: phenoml.fhir.ExecuteBundleFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): core.HttpResponsePromise<phenoml.fhir.FhirBundle> {
        return core.HttpResponsePromise.fromPromise(this.__executeBundle(request, requestOptions));
    }

    private async __executeBundle(
        request: phenoml.fhir.ExecuteBundleFhirRequest,
        requestOptions?: Fhir.RequestOptions,
    ): Promise<core.WithRawResponse<phenoml.fhir.FhirBundle>> {
        const { fhir_provider_id: fhirProviderId, "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf != null ? phenomlOnBehalfOf : undefined,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                `fhir-provider/${core.url.encodePathParam(fhirProviderId)}/fhir`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/fhir+json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as phenoml.fhir.FhirBundle, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.fhir.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.fhir.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new phenoml.fhir.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.phenomlError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.phenomlTimeoutError(
                    "Timeout exceeded when calling POST /fhir-provider/{fhir_provider_id}/fhir.",
                );
            case "unknown":
                throw new errors.phenomlError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
