// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "Medical Assistant System Prompt",
 *         content: "You are a helpful medical assistant specialized in FHIR data processing..."
 *     }
 */
export interface AgentPromptsCreateRequest {
    /** Prompt name */
    name: string;
    /** Prompt description */
    description?: string;
    /** Prompt content */
    content: string;
    /** Whether this is a default prompt */
    is_default?: boolean;
    /** Tags for categorizing the prompt */
    tags?: string[];
}
