// This file was auto-generated by Fern from our API Definition.

/** Authentication method for the FHIR provider. Only one authentication method can be used at a time, but these can be rotated on the FHIR Provider as needed. For the 'token_passthrough' authentication method, you must provide the token in the X-Phenoml-Fhir-Provider  header in the format {fhir_provider_id}:{oauth2_token}. For the 'on_behalf_of' authentication method, you must provide the Patient or Practitioner reference in the  X-Phenoml-On-Behalf-Of header in the format Patient/{uuid} or Practitioner/{uuid}. This only works for the medplum provider currently. More on the authentication headers and how to structure them can be found in the FHIR Proxy, Tools and Agent documentation. */
export const AuthMethod = {
    ClientSecret: "client_secret",
    GoogleHealthcare: "google_healthcare",
    Jwt: "jwt",
    OnBehalfOf: "on_behalf_of",
    TokenPassthrough: "token_passthrough",
    None: "none",
} as const;
export type AuthMethod = (typeof AuthMethod)[keyof typeof AuthMethod];
