// This file was auto-generated by Fern from our API Definition.

/**
 * Authentication method for the FHIR provider. Only one authentication method can be used at a time,
 * but these can be rotated on the FHIR Provider as needed.
 *
 * **Scope behavior by auth method:**
 * - `client_secret`, `jwt`, `on_behalf_of`: Scopes are included in the OAuth token request.
 *   They can be configured using the `role` or `scopes` field. If neither is specified, provider-specific
 *   default scopes derived from a default role are used.
 * - `google_healthcare`: Uses a fixed Google Cloud Healthcare scope. Specifying `role` or `scopes` will
 *   return an error.
 * - `token_passthrough`: The caller provides their own bearer token via the X-Phenoml-Fhir-Provider header
 *   as one or more comma-separated {fhir_provider_id}:{oauth2_token} pairs. Specifying `role` or `scopes`
 *   will return an error.
 * - `none`: No authentication is performed. Specifying `role` or `scopes` will return an error.
 *
 * For the `on_behalf_of` authentication method, you must also provide the Patient or Practitioner reference
 * in the X-Phenoml-On-Behalf-Of header in the format Patient/{uuid} or Practitioner/{uuid}. This only works
 * for the medplum provider currently.
 *
 * More on the authentication headers and how to structure them can be found in the FHIR Proxy, Tools and
 * Agent documentation.
 */
export const AuthMethod = {
    ClientSecret: "client_secret",
    GoogleHealthcare: "google_healthcare",
    Jwt: "jwt",
    OnBehalfOf: "on_behalf_of",
    TokenPassthrough: "token_passthrough",
    None: "none",
} as const;
export type AuthMethod = (typeof AuthMethod)[keyof typeof AuthMethod];
