// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../index.js";

export interface ClientSecretAuth {
    /** OAuth client ID */
    client_id: string;
    /** OAuth client secret */
    client_secret: string;
    role?: PhenoML.fhirProvider.Role | undefined;
    /** OAuth scopes to request. Cannot be specified with role. If neither role nor scopes are specified, the provider-specific default role will be used. */
    scopes?: string | undefined;
}
