// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../index.js";

export interface FhirProviderTemplate {
    /** Unique identifier for the FHIR provider */
    id?: string;
    /** Display name for the FHIR provider */
    name?: string;
    /** Optional description of the FHIR provider */
    description?: string;
    provider?: PhenoML.fhirProvider.Provider;
    /** Base URL of the FHIR server */
    base_url?: string;
    /** OAuth client ID. Deprecated: use client_id on FhirProviderAuthConfig instead. Retained for backward compatibility with existing providers. */
    client_id?: string;
    /** Map of authentication configurations (key is auth_config_id) */
    auth_configs?: Record<string, PhenoML.fhirProvider.FhirProviderAuthConfig>;
    /** Timestamp when the provider was last updated */
    last_updated?: string;
}
