// This file was auto-generated by Fern from our API Definition.

export interface FhirQueryResponse {
    success?: boolean;
    /** HTTP status code from the FHIR server response */
    status?: number;
    message?: string;
    data?: FhirQueryResponse.Data;
}

export namespace FhirQueryResponse {
    export type Data =
        /**
         * FHIR Bundle containing multiple resources */
        | Record<string, unknown>
        /**
         * Raw response text if not valid JSON */
        | string;
}
