// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

/**
 * Response payload for a single FHIR Provider operation.
 */
export interface FhirProviderResponse {
    success?: boolean | undefined;
    message?: string | undefined;
    /** Provider details. Sandbox providers return FhirProviderSandboxInfo. */
    data?: FhirProviderResponse.Data | undefined;
}

export namespace FhirProviderResponse {
    /**
     * Provider details. Sandbox providers return FhirProviderSandboxInfo.
     */
    export type Data = phenoml.fhirProvider.FhirProviderTemplate | phenoml.fhirProvider.FhirProviderSandboxInfo;
}
