// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

export interface GoogleHealthcareAuth {
    service_account_key: phenoml.fhirProvider.ServiceAccountKey;
}
