/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * JSON Web Key structure for RSA keys used in JWT authentication. Keys are automatically generated using RSA-2048 with RS384 signing algorithm. The Key ID (kid) is derived from a SHA256 hash of the public key PEM format.
 */
export interface JsonWebKey {
    /** Key Type */
    kty?: string;
    /** Usage (sig for signature) */
    use?: string;
    /** Key ID - SHA256 hash of the public key PEM (including headers) encoded as base64url. Generated by taking the public key in PEM format, hashing with SHA256, then base64url encoding (replacing + with -, / with _, and removing padding). */
    kid?: string;
    /** Algorithm used for JWT signing (RSA with SHA-384) */
    alg?: string;
    /** RSA Modulus (base64url encoded) */
    n?: string;
    /** RSA Exponent (base64url encoded) */
    e?: string;
}
