// This file was auto-generated by Fern from our API Definition.

/** Roles available for Phenostore providers (default: SmartV2Read) */
export const PhenostoreRole = {
    SmartV2Admin: "SmartV2Admin",
    SmartV2Read: "SmartV2Read",
    SmartV2Write: "SmartV2Write",
} as const;
export type PhenostoreRole = (typeof PhenostoreRole)[keyof typeof PhenostoreRole];
