// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as phenoml from "../../../index.js";

export declare namespace Fhir2OmopClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Fhir2OmopClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<Fhir2OmopClient.Options>;

    constructor(options: Fhir2OmopClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows,
     * grouped by destination table in `tables`.
     *
     * Current resource coverage:
     * - `Patient` -> `person`; `deceased[x]` can also produce `death`, and the
     *   first address can produce `location`
     * - `observation_period` -> one derived row per person with dated visit,
     *   clinical, or death rows, spanning those dates
     * - `Location` -> `location` and `care_site`
     * - `Organization` -> `care_site`; its first address can produce `location`
     * - `HealthcareService` -> `care_site`
     * - `Practitioner` and `PractitionerRole` -> `provider`
     * - `Encounter` -> `visit_occurrence`
     * - `Condition` -> `condition_occurrence`
     * - `Procedure` -> `procedure_occurrence`
     * - `MedicationRequest`, `MedicationStatement`, and
     *   `MedicationAdministration` -> `drug_exposure`
     * - `Immunization` -> `drug_exposure`
     * - `Observation` -> `measurement` or `observation`. For coded
     *   Observations, the resolved OMOP concept domain selects the table; value
     *   form only breaks ties. For text-only Observations, numeric values route
     *   to `measurement` and nonnumeric values to `observation`.
     * - `AllergyIntolerance` -> `observation`
     *
     * `Medication` is reference data for medication resources; it does not
     * create its own row because OMOP CDM has no Medication table. Administrative
     * linkages (provider, care site, and location) are best-effort and limited to
     * references supplied in the request. Their supporting concepts, including
     * provider specialty, country, and place of service, are not mapped.
     *
     * `DiagnosticReport`, `ServiceRequest`, `CarePlan`, `DocumentReference`,
     * `Composition`, `Specimen`, `DeviceUseStatement`, `Coverage`, `Claim`, and
     * other unsupported resource types are accepted in a Bundle but ignored: they
     * create no row and no `dropped` entry. `dropped` is reserved for supported
     * row-producing resources that could not be shaped because the subject/patient,
     * clinical code/text, or medication data was not usable. A single-Patient
     * Bundle can attribute a supported clinical resource with a missing or
     * unresolvable subject to that sole person; in a multi-Patient Bundle, that
     * resource is dropped instead.
     *
     * Coded Observation routing is selected from the resolved OMOP concept
     * domain. Numeric and nonnumeric `value[x]` forms establish the preferred
     * target only when the code is valid for both tables. A text-only
     * Observation has no resolver target, so numeric values route to
     * `measurement` and nonnumeric values to `observation`. Numeric values
     * populate `value_as_number` in the selected row; nonnumeric values
     * populate `value_as_string` for an `observation` or `value_source_value`
     * for a `measurement`. `valueCodeableConcept` remains source text and does
     * not populate `value_as_concept_id`; other unsupported `value[x]` forms
     * and Observation components do not populate separate converted values. A
     * numeric comparator (`<`, `<=`, `>`, `>=`) is represented only by a
     * measurement's `operator_concept_id`; units remain source text and have
     * `unit_concept_id` of `0`.
     *
     * A single standard OMOP `concept_id` is selected for each clinical row
     * after considering all of the resource's supplied codings. Alongside the
     * OMOP rows grouped by table (`tables`), the response carries `mappings`
     * (an entry for every source coding, linked back to the row it produced),
     * `dropped` (resources that could not be shaped into a row),
     * `vocab_version` (the OMOP vocabulary release codes were resolved
     * against), and a small `summary` of the resolution outcomes.
     *
     * A `concept_id` of `0` is reported, not omitted (OMOP "no matching
     * concept" semantics): it covers both a coding with no standard match
     * (`UNMAPPED`) and an unverified suggestion for a text-only resource
     * (`UNCHECKED`). Demographic, visit, categorical-value, and unit concept
     * fields currently remain `0`; the one populated non-resolved concept is
     * measurement
     * `operator_concept_id`, set from a value comparator (`<`, `<=`, `>`, `>=`)
     * rather than terminology resolution. Clinical `*_source_value` fields
     * preserve the selected FHIR coding (`system#code`, or `code` when no
     * system is supplied), falling back to source text for text-only resources.
     * Known OID-form coding systems are accepted as either FHIR OID URNs (for
     * example, `urn:oid:2.16.840.1.113883.6.1` for LOINC) or bare OIDs, and
     * are normalized to their canonical system URLs before terminology
     * resolution. `*_source_value` and `mappings[].source_system` report that
     * canonical URL, so the OID and URL forms produce the same mapping. An
     * unknown OID is not rewritten and may be `UNMAPPED`.
     * Other `*_source_value` fields preserve row-specific raw source values,
     * such as resource identifiers, names, units, or status codes, and
     * `*_type_concept_id` is set to `32817` (EHR).
     *
     * Medication codes are resolved whether they appear inline
     * (`medicationCodeableConcept`) or via a `medicationReference` to a contained,
     * relative (`Type/id`), or bundle-entry (`urn:uuid`) `Medication` resource.
     * Resources that cannot be shaped into a row — a medication with no usable
     * code, resolvable reference, or display, or any clinical resource whose
     * subject/patient reference cannot be tied to a person — are reported under
     * `dropped` rather than emitted as blank rows. The Bundle must contain at
     * least one Patient resource.
     *
     * All row IDs start at `1` for each request and are not stable or global.
     * For clinical conversion rows whose resource supplies an `id`, `mappings`
     * associates each row with that source FHIR resource ID. A `person` row
     * retains the Patient ID or its first identifier value in
     * `person_source_value`, when present; other reference and derived rows do
     * not uniformly carry a FHIR resource ID. Input resources without those
     * source identifiers cannot be correlated across responses from the
     * returned rows alone. Consumers combining responses need to establish
     * their own stable keys and remap every primary and foreign key together.
     *
     * @param {phenoml.fhir2Omop.CreateOmopRequest} request
     * @param {Fhir2OmopClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.fhir2Omop.BadRequestError}
     * @throws {@link phenoml.fhir2Omop.UnauthorizedError}
     * @throws {@link phenoml.fhir2Omop.InternalServerError}
     * @throws {@link phenoml.fhir2Omop.ServiceUnavailableError}
     * @throws {@link errors.phenomlError}
     * @throws {@link errors.phenomlTimeoutError}
     *
     * @example
     *     await client.fhir2Omop.create({
     *         fhir_resources: {
     *             "resourceType": "Bundle",
     *             "type": "collection",
     *             "entry": [
     *                 {
     *                     "resource": {
     *                         "resourceType": "Patient",
     *                         "id": "patient-1",
     *                         "gender": "female",
     *                         "birthDate": "1985-07-22"
     *                     }
     *                 },
     *                 {
     *                     "resource": {
     *                         "resourceType": "Condition",
     *                         "id": "condition-1",
     *                         "subject": {
     *                             "reference": "Patient/patient-1"
     *                         },
     *                         "code": {
     *                             "coding": [
     *                                 {
     *                                     "system": "http://snomed.info/sct",
     *                                     "code": "44054006",
     *                                     "display": "Type 2 diabetes mellitus"
     *                                 }
     *                             ]
     *                         },
     *                         "onsetDateTime": "2024-01-15"
     *                     }
     *                 },
     *                 {
     *                     "resource": {
     *                         "resourceType": "MedicationRequest",
     *                         "id": "medreq-1",
     *                         "status": "active",
     *                         "subject": {
     *                             "reference": "Patient/patient-1"
     *                         },
     *                         "medicationReference": {
     *                             "reference": "#med0"
     *                         },
     *                         "authoredOn": "2024-01-16",
     *                         "contained": [
     *                             {
     *                                 "resourceType": "Medication",
     *                                 "id": "med0",
     *                                 "code": {
     *                                     "coding": [
     *                                         {
     *                                             "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
     *                                             "code": "860975",
     *                                             "display": "metformin hydrochloride 500 MG"
     *                                         }
     *                                     ]
     *                                 }
     *                             }
     *                         ]
     *                     }
     *                 }
     *             ]
     *         }
     *     })
     *
     * @example
     *     await client.fhir2Omop.create({
     *         fhir_resources: {
     *             "resourceType": "Bundle",
     *             "type": "collection",
     *             "entry": [
     *                 {
     *                     "resource": {
     *                         "resourceType": "Patient",
     *                         "id": "patient-1"
     *                     }
     *                 },
     *                 {
     *                     "resource": {
     *                         "resourceType": "Observation",
     *                         "id": "hemoglobin-1",
     *                         "subject": {
     *                             "reference": "Patient/patient-1"
     *                         },
     *                         "code": {
     *                             "coding": [
     *                                 {
     *                                     "system": "urn:oid:2.16.840.1.113883.6.1",
     *                                     "code": "718-7",
     *                                     "display": "Hemoglobin"
     *                                 }
     *                             ]
     *                         },
     *                         "valueQuantity": {
     *                             "value": 13.5,
     *                             "unit": "g/dL"
     *                         }
     *                     }
     *                 }
     *             ]
     *         }
     *     })
     */
    public create(
        request: phenoml.fhir2Omop.CreateOmopRequest,
        requestOptions?: Fhir2OmopClient.RequestOptions,
    ): core.HttpResponsePromise<phenoml.fhir2Omop.CreateOmopResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: phenoml.fhir2Omop.CreateOmopRequest,
        requestOptions?: Fhir2OmopClient.RequestOptions,
    ): Promise<core.WithRawResponse<phenoml.fhir2Omop.CreateOmopResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                "fhir2omop/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as phenoml.fhir2Omop.CreateOmopResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.fhir2Omop.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.fhir2Omop.UnauthorizedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new phenoml.fhir2Omop.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 503:
                    throw new phenoml.fhir2Omop.ServiceUnavailableError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/fhir2omop/create");
    }
}
