// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request_id: "submit-2025-09-02-batch-001"
 *     }
 */
export interface CreateBatchRequest {
    /**
     * Optional client idempotency token. A retried create with the same
     * token returns the original job instead of opening a second one.
     */
    request_id?: string;
}
