// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

export interface ImplementationGuideListResponse {
    implementation_guides?: phenoml.implementationGuides.ImplementationGuideSummary[] | undefined;
}
