// This file was auto-generated by Fern from our API Definition.

export interface ConditionOccurrenceRow {
    condition_occurrence_id?: number | undefined;
    person_id?: number | undefined;
    condition_concept_id?: number | undefined;
    condition_start_date?: string | undefined;
    condition_start_datetime?: string | undefined;
    condition_end_date?: string | undefined;
    condition_type_concept_id?: number | undefined;
    visit_occurrence_id?: number | undefined;
    condition_source_value?: string | undefined;
    condition_source_concept_id?: number | undefined;
    condition_status_source_value?: string | undefined;
}
