// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

export interface CreateOmopResponse {
    success?: boolean | undefined;
    message?: string | undefined;
    /**
     * Resolution mode. `resolved` (default) means clinical `concept_id`s were
     * filled by the concept-resolver service; `structural` means no resolver
     * was configured, so all clinical `concept_id`s are `0`. Reflects which
     * resolver is wired, not the path an individual coding took — per-coding
     * degradation is surfaced in `scan_summary`, not the mode.
     */
    mode?: string | undefined;
    tables?: phenoml.fhir2Omop.OmopTables | undefined;
    /** One Usagi-shaped entry per source coding routed through concept resolution. */
    report?: phenoml.fhir2Omop.MappingReportEntry[] | undefined;
    scan_summary?: phenoml.fhir2Omop.ScanSummary | undefined;
}
