// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

export interface CreateOmopResponse {
    success?: boolean | undefined;
    message?: string | undefined;
    tables?: phenoml.fhir2Omop.OmopTables | undefined;
    /** One entry per source coding (or one entry for a text-only resource with no coding), describing how it resolved and linking back to the row it produced. */
    mappings?: phenoml.fhir2Omop.MappingEntry[] | undefined;
    /**
     * Supported resource instances that could not be shaped into an OMOP
     * row because required subject/patient, code, or medication reference
     * data was missing. Unsupported resource types are ignored and do not
     * appear here.
     */
    dropped?: phenoml.fhir2Omop.DroppedResource[] | undefined;
    /**
     * The OMOP vocabulary release returned for coded concept resolution
     * (for example, "v20240229"), for reproducibility. It is generally
     * absent for requests containing only text-only resources.
     */
    vocab_version?: string | undefined;
    summary?: phenoml.fhir2Omop.Summary | undefined;
}
