// This file was auto-generated by Fern from our API Definition.

export interface DroppedResource {
    resource_type?: string | undefined;
    resource_id?: string | undefined;
    reason?: string | undefined;
}
