// This file was auto-generated by Fern from our API Definition.

/**
 * How one source coding (or a text-only primary resource's free text) resolved to an OMOP standard concept. A coded medication route is a separate entry linked to the same drug_exposure row as its medication or vaccine coding.
 */
export interface MappingEntry {
    resource_type?: string | undefined;
    resource_id?: string | undefined;
    omop_table?: string | undefined;
    /**
     * The id of the OMOP row this coding produced (e.g. `condition_occurrence_id`),
     * within `omop_table`. A resource with multiple codings yields one entry
     * per coding, all sharing this id.
     */
    omop_id?: number | undefined;
    source_system?: string | undefined;
    source_code?: string | undefined;
    source_name?: string | undefined;
    target_vocabulary?: string | undefined;
    /**
     * The standard concept's own code: the source code itself for an
     * ALREADY_STANDARD row, the standard concept's code for a MAPPED row,
     * or the suggested code for an UNCHECKED row. Omitted for UNMAPPED
     * rows.
     */
    target_code?: string | undefined;
    target_name?: string | undefined;
    /**
     * ALREADY_STANDARD (source coding is already a standard OMOP concept),
     * MAPPED (source coding was mapped to a standard concept), UNCHECKED (a
     * standard code was suggested — e.g. for a text-only resource — but not
     * verified against the OMOP vocabulary, so `concept_id` stays `0`), or
     * UNMAPPED (no standard concept found).
     */
    mapping_status?: MappingEntry.MappingStatus | undefined;
    note?: string | undefined;
}

export namespace MappingEntry {
    /**
     * ALREADY_STANDARD (source coding is already a standard OMOP concept),
     * MAPPED (source coding was mapped to a standard concept), UNCHECKED (a
     * standard code was suggested — e.g. for a text-only resource — but not
     * verified against the OMOP vocabulary, so `concept_id` stays `0`), or
     * UNMAPPED (no standard concept found).
     */
    export const MappingStatus = {
        AlreadyStandard: "ALREADY_STANDARD",
        Mapped: "MAPPED",
        Unchecked: "UNCHECKED",
        Unmapped: "UNMAPPED",
    } as const;
    export type MappingStatus = (typeof MappingStatus)[keyof typeof MappingStatus];
}
