// This file was auto-generated by Fern from our API Definition.

/**
 * One source_to_concept_map-style mapping suggestion (Usagi-shaped).
 */
export interface MappingReportEntry {
    resource_type?: string | undefined;
    resource_id?: string | undefined;
    omop_table?: string | undefined;
    source_system?: string | undefined;
    source_code?: string | undefined;
    source_name?: string | undefined;
    target_vocabulary?: string | undefined;
    /**
     * Standard concept code. Set when a coding is matched by the structural
     * (construe) tier — an already-standard code taken verbatim, or a
     * construe-suggested code — which is every match in structural mode and,
     * in resolved mode, codings for text-only resources or ones that fell back
     * when the resolver was unavailable. Omitted for codings resolved directly
     * by the concept-resolver service, which returns the standard concept's
     * id, name, and vocabulary but not its `concept_code`.
     */
    target_code?: string | undefined;
    target_name?: string | undefined;
    /**
     * ALREADY_STANDARD (source already in the target standard vocabulary),
     * MAPPED (resolved to a standard concept via the OMOP "Maps to" crosswalk
     * or UMLS-CUI bridge; resolved mode only), UNCHECKED (an unreviewed
     * construe suggestion; structural / fallback only), or UNMAPPED (no
     * candidate found).
     */
    mapping_status?: string | undefined;
    note?: string | undefined;
}
