// This file was auto-generated by Fern from our API Definition.

/**
 * How one source coding (or a text-only primary resource's free text) resolved to an OMOP standard concept. `omop_table`, `omop_field`, and `omop_id` link it to the row and concept field it produced. A coded medication route is a separate entry linked to the same drug_exposure row as its medication or vaccine coding. `selected` identifies the coding rendered in the associated row's `*_source_value`; it is false for alternate codings and text-only rows.
 */
export interface MappingEntry {
    resource_type?: string | undefined;
    resource_id?: string | undefined;
    omop_table?: string | undefined;
    /**
     * The id of the OMOP row this coding produced (e.g. `condition_occurrence_id`),
     * within `omop_table`. A resource with multiple codings yields one entry
     * per coding, all sharing this id.
     */
    omop_id?: number | undefined;
    /** The OMOP concept-ID field populated from this source coding, such as `condition_concept_id`, `route_concept_id`, or `race_concept_id`. */
    omop_field?: string | undefined;
    source_system?: string | undefined;
    source_code?: string | undefined;
    source_name?: string | undefined;
    target_vocabulary?: string | undefined;
    /**
     * The standard concept's own code: the source code itself for an
     * ALREADY_STANDARD row, the standard concept's code for a MAPPED row,
     * or the suggested code for an UNCHECKED row. Omitted for UNMAPPED
     * rows.
     */
    target_code?: string | undefined;
    target_name?: string | undefined;
    /**
     * ALREADY_STANDARD (source coding is already a standard OMOP concept),
     * MAPPED (source coding was mapped to a standard concept), UNCHECKED (a
     * standard code was suggested for a text-only resource but not verified
     * against the OMOP vocabulary, so `concept_id` stays `0`), or UNMAPPED
     * (no standard concept found).
     */
    mapping_status?: MappingEntry.MappingStatus | undefined;
    /** Whether this source coding was selected for the linked row's `*_source_value` field. Always present; false for alternate codings and text-only rows. For a Patient demographic, it marks the code that determined the PERSON field or race `observation` row, even when that code has no concept; it is false for race and ethnicity null flavors, conflicting values, a Patient `gender` overridden by birth sex, and race categories that did not determine the field. */
    selected: boolean;
    /**
     * Additional context for the entry. A coded route is noted as
     * `FHIR route`. Patient demographic entries name their source and, when
     * not applied, why:
     * - `US Core birth sex`; `US Core birth sex; null flavor`;
     *   `US Core birth sex; outside value set`;
     *   `US Core birth sex; conflicting values`
     * - `FHIR administrative gender; assumed sex at birth`;
     *   `FHIR administrative gender; not a sex-at-birth value`;
     *   `FHIR administrative gender; not used, birth sex supplied`
     * - `US Core race OMB category`;
     *   `US Core race OMB category; more than one race` (linked to its
     *   `observation` race row); `US Core race; null flavor`
     * - `US Core ethnicity OMB category`;
     *   `US Core ethnicity OMB category; conflicting categories`;
     *   `US Core ethnicity; null flavor`
     */
    note?: string | undefined;
}

export namespace MappingEntry {
    /**
     * ALREADY_STANDARD (source coding is already a standard OMOP concept),
     * MAPPED (source coding was mapped to a standard concept), UNCHECKED (a
     * standard code was suggested for a text-only resource but not verified
     * against the OMOP vocabulary, so `concept_id` stays `0`), or UNMAPPED
     * (no standard concept found).
     */
    export const MappingStatus = {
        AlreadyStandard: "ALREADY_STANDARD",
        Mapped: "MAPPED",
        Unchecked: "UNCHECKED",
        Unmapped: "UNMAPPED",
    } as const;
    export type MappingStatus = (typeof MappingStatus)[keyof typeof MappingStatus];
}
