// This file was auto-generated by Fern from our API Definition.

export interface MeasurementRow {
    measurement_id?: number | undefined;
    person_id?: number | undefined;
    measurement_concept_id?: number | undefined;
    measurement_date?: string | undefined;
    measurement_datetime?: string | undefined;
    measurement_type_concept_id?: number | undefined;
    value_as_number?: number | undefined;
    value_as_concept_id?: number | undefined;
    unit_concept_id?: number | undefined;
    range_low?: number | undefined;
    range_high?: number | undefined;
    measurement_source_value?: string | undefined;
    measurement_source_concept_id?: number | undefined;
    unit_source_value?: string | undefined;
    value_source_value?: string | undefined;
}
