// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

/**
 * OMOP CDM v5.4 rows grouped by destination table.
 */
export interface OmopTables {
    person?: phenoml.fhir2Omop.PersonRow[] | undefined;
    visit_occurrence?: phenoml.fhir2Omop.VisitOccurrenceRow[] | undefined;
    condition_occurrence?: phenoml.fhir2Omop.ConditionOccurrenceRow[] | undefined;
    drug_exposure?: phenoml.fhir2Omop.DrugExposureRow[] | undefined;
    procedure_occurrence?: phenoml.fhir2Omop.ProcedureOccurrenceRow[] | undefined;
    measurement?: phenoml.fhir2Omop.MeasurementRow[] | undefined;
    observation?: phenoml.fhir2Omop.ObservationRow[] | undefined;
}
