// This file was auto-generated by Fern from our API Definition.

/**
 * The logical identifier supplied on a PractitionerRole's practitioner reference.
 */
export interface ProviderRolePractitionerIdentifier {
    system?: string | undefined;
    value: string;
}
