// This file was auto-generated by Fern from our API Definition.

import * as phenoml from "../../../src/api/index";
import { phenomlClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockPhenoMloAuth } from "../mockAuth";

describe("AuthClient", () => {
    test("generateToken (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "test_client_id",
            clientSecret: "test_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { username: "username", password: "password" };
        const rawResponseBody = { token: "token" };
        server
            .mockEndpoint()
            .post("/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authtoken.auth.generateToken({
            username: "username",
            password: "password",
        });
        expect(response).toEqual({
            token: "token",
        });
    });

    test("generateToken (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "test_client_id",
            clientSecret: "test_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { username: "username", password: "password" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authtoken.auth.generateToken({
                username: "username",
                password: "password",
            });
        }).rejects.toThrow(phenoml.authtoken.BadRequestError);
    });

    test("generateToken (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "test_client_id",
            clientSecret: "test_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { username: "username", password: "password" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authtoken.auth.generateToken({
                username: "username",
                password: "password",
            });
        }).rejects.toThrow(phenoml.authtoken.UnauthorizedError);
    });

    test("getToken (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "test_client_id",
            clientSecret: "test_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { access_token: "access_token", token_type: "Bearer", expires_in: 172800 };
        server
            .mockEndpoint()
            .post("/v2/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.authtoken.auth.getToken();
        expect(response).toEqual({
            access_token: "access_token",
            token_type: "Bearer",
            expires_in: 172800,
        });
    });

    test("getToken (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "test_client_id",
            clientSecret: "test_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v2/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authtoken.auth.getToken();
        }).rejects.toThrow(phenoml.authtoken.BadRequestError);
    });

    test("getToken (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "test_client_id",
            clientSecret: "test_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v2/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authtoken.auth.getToken();
        }).rejects.toThrow(phenoml.authtoken.UnauthorizedError);
    });

    test("getToken (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "test_client_id",
            clientSecret: "test_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v2/auth/token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.authtoken.auth.getToken();
        }).rejects.toThrow(phenoml.authtoken.InternalServerError);
    });
});
