// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mcp_server_tool_id: "mcp_server_tool_id"
 *     }
 */
export interface GetToolsRequest {
    /** ID of the MCP server tool to retrieve */
    mcp_server_tool_id: string;
}
