// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

/**
 * A page of per-item result statuses, without the job counts.
 */
export interface ResultsPageResponse {
    results: phenoml.lang2FhirBatch.BatchItemStatus[];
    /** Cursor for the next page, when has_more is true. */
    next_cursor?: string | undefined;
    /** Whether more results remain beyond this page. */
    has_more: boolean;
}
