// This file was auto-generated by Fern from our API Definition.

import * as phenoml from "../../../index.js";

export interface CohortResponse {
    /** Whether the cohort analysis was successful */
    success?: boolean;
    /** Status message with details about the analysis */
    message?: string;
    /** Array of patient IDs that match the cohort criteria */
    patientIds?: string[];
    /** Total number of patients in the cohort */
    patientCount?: number;
    /** Individual search concepts that were identified and executed */
    queries?: phenoml.tools.SearchConcept[];
}
