/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Provider-specific configuration and metadata
 */
export interface FhirClientConfig {
    /** FHIR store ID for Google Healthcare provider */
    fhir_store_id?: string;
    /** Email address to use for On-Behalf-Of requests (Medplum only). If provided, the request will be made on behalf of the Patient or Practitioner with this email address. */
    on_behalf_of_email?: string;
}
