// This file was auto-generated by Fern from our API Definition.

export interface Lang2FhirAndSearchResponse {
    /** The FHIR resource type identified for the search */
    resource_type?: string;
    /** FHIR search parameters in standard format */
    search_params?: string;
    /** Array of FHIR resources returned from the search */
    fhir_results?: Record<string, unknown>[];
    success?: boolean;
    /** Status message */
    message?: string;
}
