// This file was auto-generated by Fern from our API Definition.

export interface Lang2FhirAndCreateResponse {
    /** The created FHIR resource */
    fhir_resource?: Record<string, unknown>;
    /** ID of the resource in the FHIR server (if successfully stored) */
    fhir_id?: string;
    success?: boolean;
    /** Status message */
    message?: string;
}
