// This file was auto-generated by Fern from our API Definition.

export interface McpServerTool {
    /** ID of the MCP server tool */
    id?: string | undefined;
    /** Name of the MCP server tool */
    name?: string | undefined;
    /** Description of the MCP server tool */
    description?: string | undefined;
    /** Input schema of the MCP server tool */
    input_schema?: Record<string, unknown> | undefined;
    /** ID of the MCP server that the tool belongs to */
    mcp_server_id?: string | undefined;
    /** URL of the MCP server */
    mcp_server_url?: string | undefined;
}
