/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A single search concept detected in cohort mode
 */
export interface SearchConcept {
    /** The FHIR resource type identified for this concept */
    resource_type?: string;
    /** FHIR search parameters for this concept */
    search_params?: string;
    /** Description of what this search represents */
    concept?: string;
    /** Whether this is an exclusion criteria */
    exclude?: boolean;
}
