// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as phenoml from "../../../index.js";
import { TemplatesClient } from "../resources/templates/client/Client.js";

export declare namespace SummaryClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SummaryClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SummaryClient.Options>;
    protected _templates: TemplatesClient | undefined;

    constructor(options: SummaryClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get templates(): TemplatesClient {
        return (this._templates ??= new TemplatesClient(this._options));
    }

    /**
     * Creates a summary from FHIR resources using one of three modes:
     * - **narrative**: Uses a template to substitute FHIR data into placeholders (requires template_id)
     * - **flatten**: Flattens FHIR resources into a searchable format for RAG/search (no template needed)
     * - **ips**: Generates an International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG. Requires a Bundle with exactly one Patient resource (returns 400 error if no Patient or multiple Patients are present). Automatically filters resources to those referencing the patient and generates sections for allergies, medications, problems, immunizations, procedures, and vital signs.
     *
     * @param {phenoml.summary.CreateSummaryRequest} request
     * @param {SummaryClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link phenoml.summary.BadRequestError}
     * @throws {@link phenoml.summary.UnauthorizedError}
     * @throws {@link phenoml.summary.ForbiddenError}
     * @throws {@link phenoml.summary.NotFoundError}
     * @throws {@link phenoml.summary.InternalServerError}
     *
     * @example
     *     await client.summary.create({
     *         mode: "narrative",
     *         template_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
     *         fhir_resources: {
     *             "resourceType": "Bundle",
     *             "type": "collection",
     *             "entry": [
     *                 {
     *                     "resource": {
     *                         "resourceType": "Patient",
     *                         "name": [
     *                             {
     *                                 "given": [
     *                                     "John"
     *                                 ],
     *                                 "family": "Doe"
     *                             }
     *                         ],
     *                         "gender": "male",
     *                         "birthDate": "1979-03-15"
     *                     }
     *                 },
     *                 {
     *                     "resource": {
     *                         "resourceType": "Condition",
     *                         "code": {
     *                             "text": "Type 2 Diabetes Mellitus"
     *                         },
     *                         "onsetDateTime": "2024-01-15"
     *                     }
     *                 }
     *             ]
     *         }
     *     })
     *
     * @example
     *     await client.summary.create({
     *         mode: "ips",
     *         fhir_resources: {
     *             "resourceType": "Bundle",
     *             "type": "collection",
     *             "entry": [
     *                 {
     *                     "resource": {
     *                         "resourceType": "Patient",
     *                         "id": "maria-garcia-001",
     *                         "name": [
     *                             {
     *                                 "given": [
     *                                     "Maria"
     *                                 ],
     *                                 "family": "Garcia"
     *                             }
     *                         ],
     *                         "gender": "female",
     *                         "birthDate": "1985-07-22"
     *                     }
     *                 },
     *                 {
     *                     "resource": {
     *                         "resourceType": "AllergyIntolerance",
     *                         "code": {
     *                             "text": "Penicillin"
     *                         },
     *                         "criticality": "high"
     *                     }
     *                 }
     *             ]
     *         }
     *     })
     */
    public create(
        request: phenoml.summary.CreateSummaryRequest,
        requestOptions?: SummaryClient.RequestOptions,
    ): core.HttpResponsePromise<phenoml.summary.CreateSummaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: phenoml.summary.CreateSummaryRequest,
        requestOptions?: SummaryClient.RequestOptions,
    ): Promise<core.WithRawResponse<phenoml.summary.CreateSummaryResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                "fhir2summary/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as phenoml.summary.CreateSummaryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new phenoml.summary.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new phenoml.summary.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new phenoml.summary.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new phenoml.summary.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new phenoml.summary.InternalServerError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.phenomlError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/fhir2summary/create");
    }
}
