// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../mock-server/MockServerPool";
import { phenomlClient } from "../../../src/Client";

describe("Workflows", () => {
    test("createFhirResource", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/tools/lang2fhir-and-create").respondWith().statusCode(200).build();

        const response = await client.workflows.createFhirResource();
        expect(response).toEqual(undefined);
    });

    test("searchFhirResources", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/tools/lang2fhir-and-search").respondWith().statusCode(200).build();

        const response = await client.workflows.searchFhirResources();
        expect(response).toEqual(undefined);
    });

    test("analyzeCohort", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/tools/cohort").respondWith().statusCode(200).build();

        const response = await client.workflows.analyzeCohort();
        expect(response).toEqual(undefined);
    });
});
