// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../mock-server/MockServerPool";
import { phenomlClient } from "../../../src/Client";

describe("McpServer", () => {
    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/tools/mcp-server/create").respondWith().statusCode(200).build();

        const response = await client.workflows.mcpServer.create();
        expect(response).toEqual(undefined);
    });

    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/tools/mcp-server/list").respondWith().statusCode(200).build();

        const response = await client.workflows.mcpServer.list();
        expect(response).toEqual(undefined);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/tools/mcp-server/mcp_server_id").respondWith().statusCode(200).build();

        const response = await client.workflows.mcpServer.get("mcp_server_id");
        expect(response).toEqual(undefined);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/tools/mcp-server/mcp_server_id").respondWith().statusCode(200).build();

        const response = await client.workflows.mcpServer.delete("mcp_server_id");
        expect(response).toEqual(undefined);
    });
});
