// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

/**
 * Opt-in faithfulness audit (honored by /lang2fhir/create/multi and /lang2fhir/document/multi). For each selected resource type an LLM checks whether selected dates and clinical code concepts are actually supported by the full source document. An unsupported individual coding is removed when another coding remains in its concept. Resources with an unsupported structural field, a profile-required coding, or no coding remaining in an affected concept, are pulled out of the returned bundle and reported under resource_review in the response.
 */
export interface ResourceReview {
    /** The resource types to audit and which date or clinical code field kinds to check. */
    targets: phenoml.lang2Fhir.ResourceReviewTarget[];
}
