// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mcp_server_id: "mcp_server_id"
 *     }
 */
export interface GetMcpServerRequest {
    /** ID of the MCP server to retrieve */
    mcp_server_id: string;
}
