// This file was auto-generated by Fern from our API Definition.

export interface CodeSystemDetails {
    /** Code system name */
    name: string;
    /** Code system version */
    version: string;
    /** Total number of codes in the system */
    code_count: number;
    /** Whether this is a built-in system (vs custom uploaded) */
    builtin: boolean;
}
