// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

export interface CrosswalkTarget {
    /** Target FHIR code-system URI. */
    system: string;
    /** Target-level reason code when this target has no matches. */
    reason_code?: string | undefined;
    /** Codes in this target system that share a UMLS CUI with the source code. */
    matches: phenoml.construe.CrosswalkMatch[];
}
