// This file was auto-generated by Fern from our API Definition.

export interface GetCodeSystemDetailResponse {
    /** Code system name */
    name: string;
    /** Code system version */
    version: string;
    /** Total number of codes in the system */
    code_count: number;
    /** Whether this is a built-in system (vs custom uploaded) */
    builtin: boolean;
    /** Processing status of the code system. Currently always "ready". */
    status: "ready";
    /** When the code system was created */
    created_at: string;
    /** When the code system was last updated */
    updated_at: string;
}
