// This file was auto-generated by Fern from our API Definition.

import type * as phenoml from "../../../index.js";

/**
 * Upload codes in JSON format. Either 'file' or 'codes' must be provided.
 * If both are provided, 'codes' takes precedence.
 */
export interface UploadRequestJson {
    /**
     * Name of the code system. Names are case-insensitive and stored uppercase.
     * Builtin system names (e.g. ICD-10-CM, SNOMED_CT_US_LITE, LOINC, CPT, etc.) are
     * reserved and cannot be used for custom uploads; attempts return HTTP 403 Forbidden.
     */
    name: string;
    /** Version of the code system */
    version: string;
    /** Optional revision number */
    revision?: number;
    /**
     * The file contents as a base64-encoded JSON array string.
     * Prefer using 'codes' instead to pass the array directly without base64 encoding.
     */
    file?: string;
    /**
     * The codes to upload as a JSON array.
     * This is the preferred way to upload JSON codes, as it avoids unnecessary base64 encoding.
     * If both 'codes' and 'file' are provided, 'codes' takes precedence.
     */
    codes?: phenoml.construe.CodeResponse[];
    /**
     * If true, replaces an existing code system with the same name and version.
     * Builtin systems cannot be replaced; attempts to do so return HTTP 403 Forbidden.
     * When false (default), uploading a duplicate returns 409 Conflict.
     */
    replace?: boolean;
    /**
     * If true, returns 202 Accepted immediately after validation and starts processing
     * in the background. Poll GET /construe/codes/systems/{name}?version={version} to
     * check when status transitions from "processing" to "ready" or "failed".
     */
    async?: boolean;
}
