// This file was auto-generated by Fern from our API Definition.

import type * as PhenoML from "../../../../../index.js";

export interface PromptsListResponse {
    success?: boolean;
    message?: string;
    prompts?: PhenoML.agent.PromptTemplate[];
}
