// This file was auto-generated by Fern from our API Definition.

import * as phenoml from "../../../src/api/index";
import { phenomlClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockPhenoMloAuth } from "../mockAuth";

describe("AgentClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "Medical Assistant",
            description: "An AI assistant for medical information processing",
            prompts: ["prompt_123"],
            tags: ["medical", "fhir"],
            provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
        };
        const rawResponseBody = {
            success: true,
            message: "Agent created successfully",
            data: {
                id: "agent_123",
                name: "Medical Assistant",
                description: "An AI assistant for medical information processing",
                prompts: ["prompt_123", "prompt_456"],
                tools: ["mcp_server_123", "mcp_server_456"],
                workflows: ["workflow_123", "workflow_456"],
                tags: ["medical", "fhir"],
                provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
            },
        };

        server
            .mockEndpoint()
            .post("/agent/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.create({
            name: "Medical Assistant",
            description: "An AI assistant for medical information processing",
            prompts: ["prompt_123"],
            tags: ["medical", "fhir"],
            provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.create({
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.create({
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.create({
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agent/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.create({
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.InternalServerError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            success: true,
            message: "Agents retrieved successfully",
            agents: [
                {
                    id: "agent_123",
                    name: "Medical Assistant",
                    description: "An AI assistant for medical information processing",
                    prompts: ["prompt_123"],
                    tools: ["mcp_server_123", "mcp_server_456"],
                    workflows: ["workflow_123", "workflow_456"],
                    tags: ["medical", "fhir"],
                    provider: ["7002b0b4-8d09-445a-bf65-0fafdaf26c35"],
                },
                {
                    id: "agent_456",
                    name: "Clinical Coding Assistant",
                    description: "Helps with ICD-10 and SNOMED coding",
                    prompts: ["prompt_456"],
                    tools: ["mcp_server_123", "mcp_server_456"],
                    workflows: ["workflow_123", "workflow_456"],
                    tags: ["coding"],
                    provider: ["7002b0b4-8d09-445a-bf65-0fafdaf26c35"],
                },
            ],
        };

        server.mockEndpoint().get("/agent/list").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agent.list({
            tags: "tags",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/list").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.list();
        }).rejects.toThrow(phenoml.agent.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/list").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.list();
        }).rejects.toThrow(phenoml.agent.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/list").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.list();
        }).rejects.toThrow(phenoml.agent.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            success: true,
            message: "Agent retrieved successfully",
            data: {
                id: "agent_123",
                name: "Medical Assistant",
                description: "An AI assistant for medical information processing",
                prompts: ["prompt_123", "prompt_456"],
                tools: ["mcp_server_123", "mcp_server_456"],
                workflows: ["workflow_123", "workflow_456"],
                tags: ["medical", "fhir"],
                provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
            },
        };

        server.mockEndpoint().get("/agent/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agent.get("id");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.get("id");
        }).rejects.toThrow(phenoml.agent.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.get("id");
        }).rejects.toThrow(phenoml.agent.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.get("id");
        }).rejects.toThrow(phenoml.agent.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agent/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.get("id");
        }).rejects.toThrow(phenoml.agent.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "Medical Assistant",
            description: "Updated description for the medical assistant",
            prompts: ["prompt_123"],
            tags: ["medical", "fhir", "updated"],
            provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
        };
        const rawResponseBody = {
            success: true,
            message: "Agent updated successfully",
            data: {
                id: "agent_123",
                name: "Medical Assistant",
                description: "An AI assistant for medical information processing",
                prompts: ["prompt_123", "prompt_456"],
                tools: ["mcp_server_123", "mcp_server_456"],
                workflows: ["workflow_123", "workflow_456"],
                tags: ["medical", "fhir"],
                provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
            },
        };

        server
            .mockEndpoint()
            .put("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.update("id", {
            name: "Medical Assistant",
            description: "Updated description for the medical assistant",
            prompts: ["prompt_123"],
            tags: ["medical", "fhir", "updated"],
            provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.update("id", {
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.update("id", {
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.update("id", {
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.update("id", {
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", prompts: ["prompts", "prompts"], provider: "provider" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.update("id", {
                name: "name",
                prompts: ["prompts", "prompts"],
                provider: "provider",
            });
        }).rejects.toThrow(phenoml.agent.InternalServerError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { success: true, message: "Agent deleted successfully" };

        server.mockEndpoint().delete("/agent/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agent.delete("id");
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/agent/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.delete("id");
        }).rejects.toThrow(phenoml.agent.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/agent/id").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.delete("id");
        }).rejects.toThrow(phenoml.agent.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/agent/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.delete("id");
        }).rejects.toThrow(phenoml.agent.NotFoundError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/agent/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agent.delete("id");
        }).rejects.toThrow(phenoml.agent.InternalServerError);
    });

    test("patch (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "replace", path: "/description", value: "patched description" },
            { op: "add", path: "/tags/-", value: "updated" },
        ];
        const rawResponseBody = {
            success: true,
            message: "Agent patched successfully",
            data: {
                id: "agent_123",
                name: "Medical Assistant",
                description: "An AI assistant for medical information processing",
                prompts: ["prompt_123", "prompt_456"],
                tools: ["mcp_server_123", "mcp_server_456"],
                workflows: ["workflow_123", "workflow_456"],
                tags: ["medical", "fhir"],
                provider: "7002b0b4-8d09-445a-bf65-0fafdaf26c35",
            },
        };

        server
            .mockEndpoint()
            .patch("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agent.patch("id", [
            {
                op: "replace",
                path: "/description",
                value: "patched description",
            },
            {
                op: "add",
                path: "/tags/-",
                value: "updated",
            },
        ]);
        expect(response).toEqual(rawResponseBody);
    });

    test("patch (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "add", path: "path" },
            { op: "add", path: "path" },
        ];
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.patch("id", [
                {
                    op: "add",
                    path: "path",
                },
                {
                    op: "add",
                    path: "path",
                },
            ]);
        }).rejects.toThrow(phenoml.agent.BadRequestError);
    });

    test("patch (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "add", path: "path" },
            { op: "add", path: "path" },
        ];
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.patch("id", [
                {
                    op: "add",
                    path: "path",
                },
                {
                    op: "add",
                    path: "path",
                },
            ]);
        }).rejects.toThrow(phenoml.agent.UnauthorizedError);
    });

    test("patch (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "add", path: "path" },
            { op: "add", path: "path" },
        ];
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.patch("id", [
                {
                    op: "add",
                    path: "path",
                },
                {
                    op: "add",
                    path: "path",
                },
            ]);
        }).rejects.toThrow(phenoml.agent.ForbiddenError);
    });

    test("patch (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "add", path: "path" },
            { op: "add", path: "path" },
        ];
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.patch("id", [
                {
                    op: "add",
                    path: "path",
                },
                {
                    op: "add",
                    path: "path",
                },
            ]);
        }).rejects.toThrow(phenoml.agent.NotFoundError);
    });

    test("patch (6)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = [
            { op: "add", path: "path" },
            { op: "add", path: "path" },
        ];
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/agent/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agent.patch("id", [
                {
                    op: "add",
                    path: "path",
                },
                {
                    op: "add",
                    path: "path",
                },
            ]);
        }).rejects.toThrow(phenoml.agent.InternalServerError);
    });
});
