// This file was auto-generated by Fern from our API Definition.

export interface UploadResponse {
    status?: string | undefined;
    name?: string | undefined;
    version?: string | undefined;
}
