// This file was auto-generated by Fern from our API Definition.

export const ListMessagesRequestRole = {
    User: "user",
    Assistant: "assistant",
    Model: "model",
    Function: "function",
} as const;
export type ListMessagesRequestRole = (typeof ListMessagesRequestRole)[keyof typeof ListMessagesRequestRole];
