// This file was auto-generated by Fern from our API Definition.

import { mockServerPool } from "../../../mock-server/MockServerPool";
import { phenomlClient } from "../../../../src/Client";

describe("Tools", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/tools/mcp-server/mcp_server_id/list").respondWith().statusCode(200).build();

        const response = await client.workflows.mcpServer.tools.list("mcp_server_id");
        expect(response).toEqual(undefined);
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/tools/mcp-server/tool/mcp_server_tool_id").respondWith().statusCode(200).build();

        const response = await client.workflows.mcpServer.tools.get("mcp_server_tool_id");
        expect(response).toEqual(undefined);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/tools/mcp-server/tool/mcp_server_tool_id").respondWith().statusCode(200).build();

        const response = await client.workflows.mcpServer.tools.delete("mcp_server_tool_id");
        expect(response).toEqual(undefined);
    });

    test("call", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ token: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .post("/tools/mcp-server/tool/mcp_server_tool_id/call")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.workflows.mcpServer.tools.call("mcp_server_tool_id");
        expect(response).toEqual(undefined);
    });
});
