// This file was auto-generated by Fern from our API Definition.

import * as phenoml from "../../../src/api/index";
import { phenomlClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockPhenoMloAuth } from "../mockAuth";

describe("SummaryTemplatesClient", () => {
    test("listTemplates (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            success: true,
            templates: [
                {
                    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    name: "Discharge Summary",
                    description: "description",
                    template:
                        "Patient <<Patient.name[0].text>>, age <<Patient.birthDate|age>>, was admitted on <<Encounter[0].period.start>> with <<Condition[0].code.coding[0].display>>.",
                    target_resources: ["Patient", "Condition", "MedicationRequest"],
                    mode: "narrative",
                    metadata: { key: "value" },
                    created_at: "2024-01-15T10:30:00Z",
                    updated_at: "2024-01-15T10:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/fhir2summary/templates")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.summaryTemplates.listTemplates();
        expect(response).toEqual(rawResponseBody);
    });

    test("listTemplates (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/fhir2summary/templates")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.listTemplates();
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("listTemplates (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/fhir2summary/templates")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.listTemplates();
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("createTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "Discharge Summary",
            example_summary:
                "Patient John Doe, age 45, was admitted on 2024-01-10 with Type 2 Diabetes. Discharged on 2024-01-15 with Metformin 500mg BID.",
            target_resources: ["Patient", "Condition", "MedicationRequest"],
            mode: "narrative",
        };
        const rawResponseBody = {
            success: true,
            message: "Template created successfully",
            template_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            template: {
                id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name: "Discharge Summary",
                description: "description",
                template:
                    "Patient <<Patient.name[0].text>>, age <<Patient.birthDate|age>>, was admitted on <<Encounter[0].period.start>> with <<Condition[0].code.coding[0].display>>. Discharged on <<Encounter[0].period.end>> with <<MedicationRequest[0].medicationCodeableConcept.coding[0].display>> <<MedicationRequest[0].dosageInstruction[0].text>>.",
                target_resources: ["Patient", "Condition", "MedicationRequest"],
                mode: "narrative",
                metadata: { key: "value" },
                created_at: "2024-01-15T10:30:00Z",
                updated_at: "2024-01-15T10:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.summaryTemplates.createTemplate({
            name: "Discharge Summary",
            example_summary:
                "Patient John Doe, age 45, was admitted on 2024-01-10 with Type 2 Diabetes. Discharged on 2024-01-15 with Metformin 500mg BID.",
            target_resources: ["Patient", "Condition", "MedicationRequest"],
            mode: "narrative",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            example_summary: "example_summary",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.createTemplate({
                name: "name",
                example_summary: "example_summary",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.BadRequestError);
    });

    test("createTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            example_summary: "example_summary",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.createTemplate({
                name: "name",
                example_summary: "example_summary",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("createTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            example_summary: "example_summary",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.createTemplate({
                name: "name",
                example_summary: "example_summary",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("getTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            success: true,
            template: {
                id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name: "Discharge Summary",
                description: "description",
                template:
                    "Patient <<Patient.name[0].text>>, age <<Patient.birthDate|age>>, was admitted on <<Encounter[0].period.start>> with <<Condition[0].code.coding[0].display>>.",
                target_resources: ["Patient", "Condition", "MedicationRequest"],
                mode: "narrative",
                metadata: { key: "value" },
                created_at: "2024-01-15T10:30:00Z",
                updated_at: "2024-01-15T10:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.summaryTemplates.getTemplate("id");
        expect(response).toEqual(rawResponseBody);
    });

    test("getTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.getTemplate("id");
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("getTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.getTemplate("id");
        }).rejects.toThrow(phenoml.summary.ForbiddenError);
    });

    test("getTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.getTemplate("id");
        }).rejects.toThrow(phenoml.summary.NotFoundError);
    });

    test("getTemplate (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.getTemplate("id");
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("updateTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "Discharge Summary",
            template:
                "Patient {{Patient.name[0].text}} was discharged on {{Encounter[0].period.end}} with {{MedicationRequest[0].medicationCodeableConcept.coding[0].display}} {{MedicationRequest[0].dosageInstruction[0].text}}.",
            target_resources: ["Patient", "Encounter", "MedicationRequest"],
            mode: "narrative",
        };
        const rawResponseBody = {
            success: true,
            message: "Template updated successfully",
            template: {
                id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name: "Discharge Summary",
                description: "description",
                template:
                    "Patient <<Patient.name[0].text>> was discharged on <<Encounter[0].period.end>> with <<MedicationRequest[0].medicationCodeableConcept.coding[0].display>> <<MedicationRequest[0].dosageInstruction[0].text>>.",
                target_resources: ["Patient", "Encounter", "MedicationRequest"],
                mode: "narrative",
                metadata: { key: "value" },
                created_at: "2024-01-15T10:30:00Z",
                updated_at: "2024-02-20T11:00:00Z",
            },
        };

        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.summaryTemplates.updateTemplate("id", {
            name: "Discharge Summary",
            template:
                "Patient {{Patient.name[0].text}} was discharged on {{Encounter[0].period.end}} with {{MedicationRequest[0].medicationCodeableConcept.coding[0].display}} {{MedicationRequest[0].dosageInstruction[0].text}}.",
            target_resources: ["Patient", "Encounter", "MedicationRequest"],
            mode: "narrative",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.updateTemplate("id", {
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.BadRequestError);
    });

    test("updateTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.updateTemplate("id", {
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("updateTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.updateTemplate("id", {
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.ForbiddenError);
    });

    test("updateTemplate (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.updateTemplate("id", {
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.NotFoundError);
    });

    test("updateTemplate (6)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.updateTemplate("id", {
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("deleteTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { success: true, message: "Template deleted successfully" };

        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.summaryTemplates.deleteTemplate("id");
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.deleteTemplate("id");
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("deleteTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.deleteTemplate("id");
        }).rejects.toThrow(phenoml.summary.ForbiddenError);
    });

    test("deleteTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.deleteTemplate("id");
        }).rejects.toThrow(phenoml.summary.NotFoundError);
    });

    test("deleteTemplate (5)", async () => {
        const server = mockServerPool.createServer();
        mockPhenoMloAuth(server);

        const client = new phenomlClient({
            maxRetries: 0,
            clientId: "your_client_id",
            clientSecret: "your_client_secret",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.summaryTemplates.deleteTemplate("id");
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });
});
