/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as phenoml from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AgentUpdateRequest {
    /** Agent name */
    name?: string;
    /** Agent description */
    description?: string;
    /** Array of prompt IDs to use for this agent */
    prompts?: string[];
    /** Whether the agent is active */
    is_active?: boolean;
    /** Tags for categorizing the agent */
    tags?: string[];
    /** FHIR provider type - can be a single provider or array of providers */
    provider?: AgentUpdateRequest.Provider;
    meta?: phenoml.agent.AgentFhirConfig;
}

export namespace AgentUpdateRequest {
    /**
     * FHIR provider type - can be a single provider or array of providers
     */
    export type Provider =
        | "medplum"
        | "google_healthcare"
        | "canvas"
        | "hapi"
        /**
         * Array of FHIR providers */
        | ("medplum" | "google_healthcare" | "canvas" | "hapi")[];
}
