/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as phenoml from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AgentUpdateRequest {
    /** Agent name */
    name?: string;
    /** Agent description */
    description?: string;
    /** Array of prompt IDs to use for this agent */
    prompts?: string[];
    /** Array of MCP server tool IDs to use for this agent */
    tools?: string[];
    /** Whether the agent is active */
    is_active?: boolean;
    /** Tags for categorizing the agent */
    tags?: string[];
    /** FHIR provider type - can be a single provider or array of providers */
    provider?: phenoml.agent.AgentProvider;
    meta?: phenoml.agent.AgentFhirConfig;
}
